### ISSUE TITLE
speed up quota client

### ISSUE THREAD

**Issue by garlick** [chaos/rquota#7]
If there are a lot of file systems to query and `quota -v` or similar is part of a system's `/etc/profile` or equivalent, login speed becomes sensitive to file system server load.

Consider making each "getquota" query in its own pthread to speed things up.

**Comment by garlick** [comment]
Some of the problems were documented here (sorry private to LLNL):

https://lc.llnl.gov/jira/browse/SAG-748

An strace in that issue shows a DNS timeout occuring, not a slow quota RPC (although the DNS lookup is probably inside glibc code that is called by the sunrpc stub)

**Comment by garlick** [comment]
As discussed in the issue above, what we're seeing is often a 5s timeout (or several of them) of the UDP based rquota RPC, e.g.
```
sendto(3, "[\331\217\234\0\0\0\0\0\0\0\2\0\1\206\253\0\0\0\1\0\0\0\1\0\0\0\1\0\0\0 "..., 88, 0, {sa_family=AF_INET, sin_port=htons(4049), sin_addr=inet_addr("134.9.6.8")}, 16) = 88
poll([{fd=3, events=POLLIN}], 1, 5000)  = 0 (Timeout)
```
Note that port 4049 is the port used for the rquota RPC on [NetApps](http://docs.netapp.com/ontap-9/index.jsp?topic=%2Fcom.netapp.doc.dot-cm-nmg%2FGUID-49D0B88F-42CF-4766-A688-1C77A0AE8BD5.html)

It seems like it normally takes the same test system about 120ms to query 26 configured file systems.  It seems to be either that, or a multiple of the 5s timeout.  Given that, perhaps we're just losing UDP packets occasionally and a simpler solution is to change reconfigure the RPC timeout.

It looks like the default "retry timeout" for UDP RPC can be changed by calling
```
       bool_t clnt_control(CLIENT *cl, int req, char *info);

              A  macro  used to change or retrieve various information about a
              client object.  req indicates the type of operation, and info is
              a  pointer  to  the information.  For both UDP and TCP, the sup‐
              ported values of req and their argument types and what  they  do
              are:

              The following operations are valid for UDP only:

                  CLSET_RETRY_TIMEOUT  struct timeval // set the retry timeout
                  CLGET_RETRY_TIMEOUT  struct timeval // get the retry timeout

              The  retry  timeout  is  the  time  that "UDP RPC" waits for the
              server to reply before retransmitting the request.
```
Perhaps if we ran with a 500ms retry timeout instead of 5000ms overall responsiveness would improve?

**Comment by garlick** [comment]
So the default behavior is to retry every 5s and give up after 25s.

My vote is to change that to retry every 100ms and give up after 1s.

That way if we lose a handful of messages, recovery will be quick.  Raising the max number of requests per server from 5 to 10 probably won't have any effect on congestion.  Giving up on any given filer after 1s seems OK given how fast quota usually responds.

If this does't work, we can look at threading, but it seems like it has a high probability of addressing the immediate problem.

**Comment by ofaaland** [comment]
> My vote is to change that to retry every 100ms and give up after 1s.

I agree.  Also, if the user wants to retry 25s later they can do it themselves; it's not like we lost a write.

**Comment by garlick** [comment]
Yup, agreed.

**Comment by garlick** [comment]
Trent attempted a test where he ran `pdsh -f 200 quota` with the proposed 1s / 100ms timeout values.  We got a lot of timeouts, e.g. that ran out the full second.   There should definitely be command line options to allow the timeout values to be tweaked so we don't have to roll a new release if the defaults prove inadequate.

We also might also want to change the default to 3s / 250ms or similar, to be a bit less aggressive on the retries, and slightly more patient.

**Comment by garlick** [comment]
FWIW, playing with the pdsh test mentioned above, setting the timeout to 2.5s / 500ms makes the timeouts totally go away.  Since we're just guessing at this, and that's exactly 1/10 of the default timeouts, let's go with that!
